sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # - openssl 
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project <project_id>
  - gcloud config set compute/zone us_central_a
  - gcloud container clusters get-creadentials <cluster_name>
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t nibrasmuhamed/test-multi-k8s -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script: 
  - docker run nibrasmuhamed/test-multi-k8s npm test coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
