apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: myingress
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
           serviceName: client-cluster-ip-service
           servicePort: 3000
        - path: /api/
          pathType: Prefix
          backend:
            serviceName: server-cluster-ip-service
            servicePort: 5000

